version: '3'

services:
  db:
    image: postgres:11
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
